# Ajustes de memoria para Gradle
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# AndroidX y Jetifier
android.useAndroidX=true
android.enableJetifier=true
kotlin.code.style=official

# DESACTIVAR CONFIGURATION CACHE (Evita choques con el plugin de Room/KSP)
org.gradle.configuration-cache=false
ksp.incremental=false
org.gradle.caching=false
